apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
    tier: backend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
        app: user
        tier: backend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: user
        tier: backend
    spec:
      containers:
      - name: user
        image: jagadevops321/user:{{ .Values.imageversion }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
        - configMapRef:
           name: user  
