apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: {{ .Values.namespace }}
  labels:
    app: user
    tier: backend
spec:
  ports:
  - port: 8080
    name: user
  selector:
    app: user
    tier: backend
