apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  ports:
  - port: 27017
    name: redis
  clusterIP: None   # For headless service the cluster ip will be none 
  selector:
    app: redis