apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    app: shipping
    tier: backend
spec:
  # modify replicas according to your case
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
        app: shipping
        tier: backend                # Upto here this is replica set definition 
  template:                             # From here POD definition starts 
    metadata:
      labels:
        app: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: jagadevops321/shipping:{{ .Values.imageversion }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 500m
        envFrom:
        - configMapRef:
           name: shipping  
