apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: {{ .Values.namespace }}
  labels:
    app: shipping
    tier: backend
spec:
  ports:
  - port: 8080
    name: shipping
  selector:
    app: shipping
    tier: backend
