apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: {{ .Values.namespace }}
  labels:
    app: catalogue
    tier: backend
spec:
  ports:
  - port: 8080
    name: catalogue
  selector:
    app: catalogue
    tier: backend
